name: .NET
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        configuration: [Debug, Dev Debug, Debug Bench, Release, Dev Release]
        include:
        - os: ubuntu-latest
          OS_NAME: Linux x64
          DOTNET_RUNTIME_IDENTIFIER: linux-x64
          RELEASE_ZIP_OS_NAME: linux_x64

        - os: macOS-latest
          OS_NAME: macOS x64
          DOTNET_RUNTIME_IDENTIFIER: osx-x64
          RELEASE_ZIP_OS_NAME: osx_x64

        - os: windows-latest
          OS_NAME: Windows x64
          DOTNET_RUNTIME_IDENTIFIER: win-x64
          RELEASE_ZIP_OS_NAME: win_x64
        
        - configuration: Debug
          BUILD_CONFIGURATION_NAME: debug
          
        - configuration: Dev Debug
          BUILD_CONFIGURATION_NAME: dev_debug
          
        - configuration: Debug Bench
          BUILD_CONFIGURATION_NAME: debug_bench
          
        - configuration: Release
          BUILD_CONFIGURATION_NAME: release
          
        - configuration: Dev Release
          BUILD_CONFIGURATION_NAME: dev_release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true

      - name: Build
        run: dotnet build -c "${{ matrix.configuration }}" --no-restore
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
      
      - name: Test
        run: dotnet test --no-build -c "${{ matrix.configuration }}"
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
          
      - name: Publish Installer
        run: dotnet publish -c "${{ matrix.configuration }}" -r "${{ matrix.DOTNET_RUNTIME_IDENTIFIER }}" --no-self-contained --output ./publish --no-restore
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.RELEASE_ZIP_OS_NAME }}-${{ matrix.BUILD_CONFIGURATION_NAME }}
          path: publish
