name: .NET
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and test
        run: dotnet build --configuration Release --no-restore
        env:
          ASPNETCORE_ENVIRONMENT: Development
          DOTNET_CLI_TELEMETRY_OPTOUT: true

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish --no-restore --runtime ${{ matrix.os }}-${{ matrix.architecture-runtime }}
        env:
          ASPNETCORE_ENVIRONMENT: Production
          DOTNET_CLI_TELEMETRY_OPTOUT: true
